services:
  imgproxy_plus:
    image: imgproxy_plus:latest
    container_name: imp
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - ${PLUS_LOCAL_PATH:-./data/}:/data
      - /onas/ssd1/aria2/:/data/aria2/
      - /onas/ssd1/:/data/ssd1/
      - ramdisk:/mnt/ramdisk
      - ./html:/usr/local/bin/html
    env_file:
      - .env
    networks:
      - imgproxy_net

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: always
    ports:
      - "6800:6800/tcp"
      - "6888:6888/udp"
      - "6888:6888/tcp"
    volumes:
      - /data/gallery/completed:/downloads/completed
      - /data/gallery/downloading:/downloads
      - ./aria2-conf:/config
    environment:
      - TZ=Asia/Shanghai
      - UMASK_SET=010
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=ariavete
      - SPECIAL_MODE=move
    networks:
      - imgproxy_net

volumes:
  ramdisk:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=512m,mode=0755"

networks:
  imgproxy_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
